-- ═══════════════════════════════════════════════════════════════
-- 근무관리 (출퇴근·급여·연차) — work-manager JSON DB 이관 (2026-08)
--
-- 보안 모델: RLS 켜고 정책 없음 → service_role(Edge Functions)로만 접근.
--            app_users와 동일. 조회는 db 프록시(읽기 전용), 수정은 wm-admin 함수.
--
-- 설계 결정 2가지 (변경 금지):
--  1) id는 정수 그대로 보존 + setval로 기존 nextId에 맞춤.
--     이유: 이관 전후 행 단위 대조가 검증 전략의 핵심.
--  2) clock_in/clock_out은 text ('YYYY-MM-DD HH:MM:SS' KST naive).
--     이유: salary.js가 clock_in.substring(11,16)으로 'HH:MM'을 잘라
--     '09:00'과 문자열 비교함. timestamptz로 바꾸면 조용히 깨진다.
--     이 결정이 급여 로직을 글자 그대로 이식 가능하게 해준다.
-- ═══════════════════════════════════════════════════════════════

-- ── 직원 ──
create table if not exists wm_employees (
  id                  integer primary key generated by default as identity,
  name                text not null,
  type                text not null check (type in ('employee','parttime')),
  hourly_rate         integer not null default 0,
  monthly_salary      integer not null default 0,
  annual_leave_total  integer not null default 15,
  transport_allowance integer not null default 0,
  fixed_clock_in      text check (fixed_clock_in ~ '^\d{2}:\d{2}$'),  -- 'HH:MM' 문자열 비교 유지
  birthday            text check (birthday ~ '^\d{4}-\d{2}-\d{2}$'),
  bank_name           text,
  bank_account        text,
  bank_holder         text,
  pin_hash            text,                                -- bcrypt. 평문 PIN 저장 금지
  pin_set_at          timestamptz,
  pin_fail_count      integer not null default 0,
  pin_locked_until    timestamptz,
  active              boolean not null default true,       -- 하드 삭제 금지 (급여 기록 보존)
  created_at          timestamptz not null default now(),
  legacy_created_at   text                                 -- 원본 ko-KR 문자열 무손실 보존
);

-- ── 출퇴근 ──
create table if not exists wm_attendance (
  id                 integer primary key generated by default as identity,
  employee_id        integer not null references wm_employees(id),
  date               date not null,
  clock_in           text not null check (clock_in  ~ '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$'),
  clock_out          text          check (clock_out ~ '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$'),
  work_minutes       integer,
  note               text,
  is_edited          boolean not null default false,
  edited_at          text,
  original_clock_in  text,
  original_clock_out text,
  source             text not null default 'kiosk'
                     check (source in ('kiosk','admin','edit_approval','migration','offline_queue')),
  created_at         timestamptz not null default now()
);
create unique index if not exists wm_attendance_emp_date on wm_attendance(employee_id, date);
create index if not exists wm_attendance_date on wm_attendance(date);

-- ── 휴가 ──
create table if not exists wm_leaves (
  id                integer primary key generated by default as identity,
  employee_id       integer not null references wm_employees(id),
  date              date not null,
  type              text not null check (type in ('annual','half','summer')),
  reason            text,
  status            text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at        timestamptz not null default now(),
  legacy_created_at text,
  reviewed_at       text
);
create unique index if not exists wm_leaves_emp_date on wm_leaves(employee_id, date) where status <> 'rejected';

-- ── 공휴일 ──
-- unique(date) 불가: 실데이터에 날짜 중복 4건 존재
-- (2028-10-03 개천절+추석, 2039-10-03, 2044-05-05 어린이날+부처님오신날, 2047-10-03)
create table if not exists wm_holidays (
  id         integer primary key generated by default as identity,
  date       date not null,
  name       text not null,
  hours      integer not null default 8,
  created_at timestamptz not null default now()
);
create unique index if not exists wm_holidays_date_name on wm_holidays(date, name);

-- ── 출퇴근 수정 신청 ──
create table if not exists wm_attendance_edits (
  id                  integer primary key generated by default as identity,
  attendance_id       integer references wm_attendance(id) on delete set null,
  employee_id         integer not null references wm_employees(id),
  date                date not null,
  original_clock_in   text,
  original_clock_out  text,
  requested_clock_in  text not null,
  requested_clock_out text,
  reason              text not null,
  status              text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at          timestamptz not null default now(),
  legacy_created_at   text,
  reviewed_at         text
);
create index if not exists wm_attendance_edits_status on wm_attendance_edits(status);

-- ── 키오스크 기기 등록 ──
-- "매장에서만 출퇴근 가능"의 1겹(기기) + 2겹(IP).
-- 원본 토큰은 서버에 저장하지 않는다 (sha256 해시만).
create table if not exists wm_devices (
  id           uuid primary key default gen_random_uuid(),
  label        text not null,
  token_hash   text unique,
  pairing_code text unique,                        -- 8자리, 등록 완료 시 null
  pairing_exp  timestamptz,
  allowed_ips  text[] not null default '{}',       -- 매장 공인 IP. 비어있으면 최초 성공 IP를 자동 학습
  enforce_ip   boolean not null default true,      -- 출퇴근 등록에만 적용
  active       boolean not null default true,
  created_at   timestamptz not null default now(),
  last_seen_at timestamptz,
  last_ip      text
);

-- ── 감사 로그 (오프라인 재전송 중복 차단 겸용) ──
create table if not exists wm_kiosk_log (
  id          bigint primary key generated always as identity,
  request_id  uuid unique,                         -- 클라이언트 생성. 재전송 멱등성 보장
  device_id   uuid references wm_devices(id),
  employee_id integer references wm_employees(id),
  actor       text,                                -- 관리자 동작이면 app_users.id
  action      text not null,
  ok          boolean not null default true,
  ip          text,
  detail      jsonb,
  at          timestamptz not null default now()
);
create index if not exists wm_kiosk_log_at on wm_kiosk_log(at desc);
create index if not exists wm_kiosk_log_emp on wm_kiosk_log(employee_id, at desc);

-- ── 조회용 뷰: pin_hash·계좌 제외 ──
-- db 프록시에는 이 뷰만 노출한다. 계좌가 필요한 화면은 wm-admin 함수로.
create or replace view wm_employees_pub as
  select id, name, type, hourly_rate, monthly_salary, annual_leave_total,
         transport_allowance, fixed_clock_in, birthday, active,
         (pin_hash is not null) as has_pin, created_at
  from wm_employees;

-- ── RLS: 켜고 정책 없음 = service_role 전용 ──
alter table wm_employees        enable row level security;
alter table wm_attendance       enable row level security;
alter table wm_leaves           enable row level security;
alter table wm_holidays         enable row level security;
alter table wm_attendance_edits enable row level security;
alter table wm_devices          enable row level security;
alter table wm_kiosk_log        enable row level security;
